server:
  port: ${APP_PORT:8096}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  max-http-request-header-size: 40KB
  shutdown: ${SHUTDOWN:graceful}
  error:
    whitelabel:
      enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: ${TIMEOUT_PER_SHUTDOWN_PHASE:10s}
  application:
    name: javapro_limits_service
  servlet:
    multipart:
      max-file-size: ${MULTIPART_FILE_MAX:10MB}
      max-request-size: ${MULTIPART_REQUEST_MAX:10MB}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: false
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    open-in-view: false
  web:
    resources:
      add-mappings: false
  flyway:
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    fail-on-missing-locations: ${FLYWAY_FAIL_ON_MISSING_LOCATIONS:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}

logging:
  config: ${LOGGING_CONFIG:classpath:logging/log4j2-local.xml}
  level:
    ROOT: ${LOGGING_LEVEL_ROOT:info}
    org.example: ${LOGGING_LEVEL:debug}
    org.hibernate.SQL: ${ORG_HIBERNATE_SQL:info}                     # для усиленного логирования - debug
    org.hibernate.orm.jdbc.bind: ${ORG_HIBERNATE_ORM_JDBC_BIND:info} # для усиленного логирования - trace

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    url: /limit-service-rest-v1.yaml # Документацию для Сваггера генерируем на основе спецификации

app:
  user-default-limit: ${USER_DEFAULT_LIMIT:10000}  # TODO добавить таблицу типа Key/Value и эндпоинт для изменения на лету
  housekeeping:
    enabled: ${HOUSEKEEPING_ENABLED:true}
    cron: ${HOUSEKEEPING_CRON:0 0 1 * * *} # в час ночи каждый день
    fetch-records-at-once: ${HOUSEKEEPING_FETCH_RECORDS_AT_ONCE:100000}
    housekeeping-max-duration:  ${HOUSEKEEPING_MAX_DURATION:PT23H}
  limit-service:
    transaction-max-duration: ${LIMIT_SERVICE_TRANSACTION_MAX_DURATION:30} # длительность транзакции задается в секундах
    max-attempts: ${LIMIT_SERVICE_MAX_ATTEMPTS:3}
    delay: ${LIMIT_SERVICE_DELAY:1000}

