openapi: 3.0.0
info:
  title: limit-service-rest-v1.yaml
  version: 1.0.0
  contact:
    name: Сухин Леонид Викторович
    email: leva1981@yandex.ru
    url: https://t.me/levaryazan
  description: API для работы с продуктовым сервисом
tags:
  -
    name: product-controller
    description: Методы работы с продуктами
  -
    name: payment-controller
    description: Методы работы с платежами
paths:
  /products/for-user:
    get:
      description: Метод предназначен для получения списка продуктов пользователя
      operationId: getUserProducts
      tags:
        - product-controller
      parameters:
        -
          name: userId
          in: query
          required: true
          allowEmptyValue: false
          description: Id пользователя
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Список продуктов пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
  /payment:
    put:
      description: Метод предназначен для обработки пользовательского платежа с использованием выбранного продукта
      operationId: putPayment
      tags:
        - payment-controller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '200':
          description: Подтверждение успешного проведения платежа
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Products:
      type: array
      description: Список продуктов пользователя
      x-field-extra-annotation: '@lombok.Builder.Default'
      items:
        $ref: '#/components/schemas/Product'
    Product:
      type: object
      description: Данные продукта
      additionalProperties: false
      required:
        - id
        - account
        - productType
      properties:
        id:
          type: integer
          format: int64
          description: Id продукта
          example: '552090181378957492'
        account:
          type: string
          minLength: 1
          maxLength: 20
          description:  Счет
        balance:
          type: integer
          format: int64
          description: Баланс
          example: '15000'
        productType:
          type: object
          description: Тип продукта
          required:
            - id
            - name
          properties:
            id:
              type: integer
              description: Id типа продукта
            name:
              type: string
              description: Название продукта
              minLength: 1
              maxLength: 100
    Payment:
      description: информация о платеже
      required:
        - productId
        - amount
      properties:
        productId:
          type: integer
          format: int64
          description: Id продукта для списания средств
          example: '552090181378957492'
        amount:
          type: integer
          format: int64
          description: Сумма к списанию
          example: '1500'
    ErrorResponse:
      type: object
      description: Типовая ошибка для передачи на front-end
      additionalProperties: false
      properties:
        timestamp:
          type: string
          format: date-time
          description: Время события на сервере
        sessionId:
          type: string
          minLength: 1
          maxLength: 100
          description: ID сессии
        errorCode:
          type: string
          minLength: 1
          maxLength: 50
          description: Код ошибки
          example: '422'
        errorMessage:
          type: string
          minLength: 1
          maxLength: 255
          description: Сообщение об ошибке
          example: Error
