openapi: 3.0.0
info:
  title: limit-service-rest-v1.yaml
  version: 1.0.0
  contact:
    name: Сухин Леонид Викторович
    email: leva1981@yandex.ru
    url: https://t.me/levaryazan
  description: API для работы с сервисом лимитов
tags:
  -
    name: limit-controller
    description: Методы работы с лимитами
paths:
  /limit:
    get:
      description: Метод возвращает текущий лимит для пользователя
      operationId: getLimit
      tags:
        - limit-controller
      parameters:
        -
          name: userId
          in: query
          required: true
          allowEmptyValue: false
          description: Id пользователя
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Текущий доступный лимит
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentLimit'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
    post:
      description: Метод пытается уменьшить текущий лимит пользователя
      operationId: postLimit
      tags:
        - limit-controller
      parameters:
        -
          name: userId
          in: query
          required: true
          allowEmptyValue: false
          description: Id пользователя
          schema:
            type: integer
            format: int64
        -
          name: value
          in: query
          required: true
          allowEmptyValue: false
          description: Значение, на которое надо уменьшить лимит
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Подтверждение успешного изменения лимита
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
  /limit/rollback:
    post:
      description: Метод предназначен для отмены применения лимита
      operationId: rollbackLimit
      tags:
        - limit-controller
      parameters:
        -
          name: userId
          in: query
          required: true
          allowEmptyValue: false
          description: Id пользователя
          schema:
            type: integer
            format: int64
        -
          name: value
          in: query
          required: true
          allowEmptyValue: false
          description: Значение, на которое надо уменьшить лимит
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Изменение лимита успешно отменено
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                oneOf:
                  -
                    $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CurrentLimit:
      type: object
      description: Идентификатор пользователя и его текущий лимит
      properties:
        userId:
          type: integer
          format: int64
          description: Id пользователя
          example: '552090181378957492'
        limit_date:
          type: string
          format: date
          description: Дата лимита
          example: '2024-06-07'
        limit:
          type: integer
          format: int64
          description: Текущий лимит пользователя
          example: '8750'
    ErrorResponse:
      type: object
      description: Типовая ошибка для передачи на front-end
      additionalProperties: false
      properties:
        timestamp:
          type: string
          format: date-time
          description: Время события на сервере
        sessionId:
          type: string
          minLength: 1
          maxLength: 100
          description: ID сессии
        errorCode:
          type: string
          minLength: 1
          maxLength: 50
          description: Код ошибки
          example: '422'
        errorMessage:
          type: string
          minLength: 1
          maxLength: 255
          description: Сообщение об ошибке
          example: Error
